name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  # ...existing trigger configuration...

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        # ...existing configuration...

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        # ...ensure that this script outputs to your designated publish directory...

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # ...change publish_dir if your build output folder is different...
